[outputs]
cors_origins=https://dashy.sphynx-ule.ts.net
cors_credentials=True
ssl_certfile=/Users/miniserver/.local/share/certs/miniserver.sphynx-ule.ts.net.crt
ssl_keyfile=/Users/miniserver/.local/share/certs/miniserver.sphynx-ule.ts.net.key
