services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config/:/config
    restart: unless-stopped
    ports:
      - "8081:8080"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=proxy
      - tsdproxy.container_port=8080
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  datadir:
