services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config/:/config
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  datadir:
