services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    restart: unless-stopped
    ports:
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - datadir:/data
      - ./config/:/config
    networks:
      - tailscale-proxy

networks:
  tailscale-proxy:
    external: true

volumes:
  datadir:
