services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    restart: unless-stopped
    ports:
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config/:/config
    networks:
      - tsdproxy-proxy

networks:
  tsdproxy-proxy:
    external: true

volumes:
  datadir:
