---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    volumes:
      - ~/container-volume/open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.openwebui.rule=Host(`chat.miniserver.home.arpa`)
      - traefik.http.services.openwebui.loadbalancer.server.port=8080
      # - traefik.http.routers.adguard.middlewares=local-ipwhitelist@file

volumes:
  open-webui:

networks:
  proxy:
    external: true
