---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    volumes:
      - ~/container-volume/open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.openwebui.rule=Host(`chat.mini.home.arpa`)
      - traefik.http.services.openwebui.loadbalancer.server.port=8080
      - tsdproxy.enable=true
      - tsdproxy.name=chat
      - tsdproxy.container_port=8080

networks:
  proxy:
    external: true
