---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    volumes:
      - ~/container-volume/open-webui:/app/backend/data
    networks:
      - traefik-proxy
      - tailscale-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.openwebui.rule=Host(`chat.mini.home.arpa`)
      - traefik.http.services.openwebui.loadbalancer.server.port=8080
      - tsdproxy.enable=true
      - tsdproxy.name=chat
      - tsdproxy.container_port=8080
    environment:
      - ENABLE_ADMIN_CHAT_ACCESS=false

networks:
  traefik-proxy:
    external: true
  tailscale-proxy:
    external: true
