services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: perplexica-searxng
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
    # ports:
    #   - 4000:8080
    networks:
      - perplexica-network

  perplexica-backend:
    image: itzcrazykns1337/perplexica-backend:main
    container_name: perplexica-backend
    restart: unless-stopped
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    # ports:
    #   - 3001:3001
    volumes:
      - ~/container-volume/perplexica/backend-dbstore:/home/perplexica/data
      - ~/container-volume/perplexica/uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - perplexica-network

  perplexica-frontend:
    image: itzcrazykns1337/perplexica-frontend:main
    container_name: perplexica-frontend
    restart: unless-stopped
    depends_on:
      - perplexica-backend
    # ports:
    #   - 3000:3000
    networks:
      - perplexica-network
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.perplexica-frontend.rule=Host(`search.miniserver.home.arpa`)
      - traefik.http.services.perplexica-frontend.loadbalancer.server.port=3000

networks:
  perplexica-network:
  proxy:
    external: true
