http:
  middlewares:
    local-ipwhitelist:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16

    rate-limit:
      rateLimit:
        average: 100
        period: 1
        burst: 100

    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/usersFile.txt"
