global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: ERROR
accessLog:
  filePath: "/logs/traefik.log"
  format: json
  filters:
    statusCodes:
      - "200-299"
      - "400-599"
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep

providers:
  providersThrottleDuration: 2s

  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

  docker:
    watch: true
    network: proxy
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    # http:
    #   #   tls:
    #   #     certResolver: myresolver
    #   #     domains:
    #   #       - main: mini.sphynx-ule.ts.net
    #   #         sans:
    #   #           - "*.mini.sphynx-ule.ts.net"
    #   middlewares:
    #     - security-headers@file
    #     - rate-limit@file

certificatesResolvers:
  myresolver:
    tailscale: {}
