---
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 8080:80/tcp
    restart: unless-stopped
    volumes:
      - ~/container-volume/adguard-home/work:/opt/adguardhome/work
      - ~/container-volume/adguard-home/conf:/opt/adguardhome/conf
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.adguard.rule=Host(`dns.example.com`)
    #  - traefik.http.services.adguard.loadbalancer.server.port=8080
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.adguard.middlewares=local-ipwhitelist@file,authelia@docker
#networks:
#  proxy:
#    external: true
