---
services:
  feishin:
    container_name: feishin
    image: "ghcr.io/jeffvli/feishin:latest"
    restart: unless-stopped
    network_mode: service:tailscale-feishin
    environment:
      - SERVER_NAME=feishin
      - SERVER_LOCK=true
      - SERVER_TYPE=navidrome
      - SERVER_URL=http://ts-navidrome:4533
      - REMOTE_URL=https://navidrome.sphynx-ule.ts.net
      - LEGACY_AUTHENTICATION=false
      - ANALYTICS_DISABLED=true

  tailscale-feishin:
    image: tailscale/tailscale:latest
    container_name: ts-feishin
    hostname: feishin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - navidrome-net
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:?TS_AUTHKEY must be set}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/ts-serve-config.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./:/config:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  tailscale-state:

networks:
  navidrome-net:
    external: true
