---
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik/
      - ~/container-volume/traefik/logs:/logs
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.miniserver.home.arpa`)
      - traefik.http.services.traefik.loadbalancer.server.port=8081
      # - traefik.http.routers.api.service=api@internal
      # - traefik.http.routers.api.middlewares=local-ipwhitelist@file
    networks:
      - proxy

networks:
  proxy:
    external: true
