---
services:
  reverse-proxy:
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# ---
# services:
#   traefik:
#     image: traefik:v3.3
#     container_name: traefik
#     restart: unless-stopped
#     ports:
#       - "80:80"
#       - "8082:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./config:/etc/traefik/
#       - ~/container-volume/traefik/logs:/logs
#     environment:
#       - TZ=Europe/Amsterdam
#     labels:
#       - traefik.enable=true
#       - traefik.http.routers.api.rule=Host(`traefik.mini.home.arpa`)
#       - traefik.http.routers.api.service=api@internal
#       - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@file
#     networks:
#       - traefik-proxy
#
# networks:
#   traefik-proxy:
#     external: true
