---
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    # command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik/
      - ~/container-volume/traefik/logs:/logs
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.miniserver.home.arpa`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=local-ipwhitelist@file
      # - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@docker
      # - traefik.http.middlewares.basic-auth-global.basicauth.users=admin:${TRAEFIK_PASSWORD:-$$apr1$$epoKf5li$$QfTMJZOCS/halv3CiIUEu0} # protect the traefik dashboard by basic auth (pw=password)
    networks:
      - proxy

networks:
  proxy:
    external: true
