---
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik/
      - ~/container-volume/traefik/logs:/logs
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.mini.home.arpa`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@file
      - tsdproxy.enable=true
      - tsdproxy.name=traefik
      - tsdproxy.container_port=8080
    networks:
      - proxy

networks:
  proxy:
    external: true
