---
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:rw
      - ./config:/etc/traefik/
      - ~/container-volume/traefik/logs:/logs
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`miniserver.sphynx-ule.ts.net`) && Path(`/proxy`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@file
      - traefik.http.routers.api.tls.certresolver=myresolver
    networks:
      - proxy

networks:
  proxy:
    external: true
