---
services:
  dashy:
    image: lissy93/dashy
    restart: unless-stopped
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.dashy.rule=Host(`home.mini.home.arpa`)
      - traefik.http.services.dashy.loadbalancer.server.port=8080
      # - tsdproxy.enable=true
      # - tsdproxy.name=home
      # - tsdproxy.container_port=8080

networks:
  traefik-proxy:
    external: true
