format = """
$os\
$memory_usage\
$localip\
$directory\
$git_branch\
$git_status\
$git_state\
$docker_context\
$fill\
$time\
\n$character"""


add_newline = false
palette = "catppuccin_mocha"

[os]
format = " [$symbol]($style)"
style = "blue"
disabled = false

[os.symbols]
Macos = "󰀶"

[memory_usage]
format = ' using [$symbol]($style) [${ram}( | ${swap})]($style) '
disabled = false
threshold = -1
symbol = ''
style = 'bold green'

[localip]
ssh_only = false
format = ' @ [$localipv4](bold teal) '
disabled = false

[directory]
format = "[ $path ]($style)"
style = "mauve"
truncation_length = 1

[git_branch]
format = "[ $branch ]($style)"
style = "peach"

[git_status]
format = "$ahead_behind$stashed$conflicted$staged$deleted$renamed$modified$typechanged$untracked"
up_to_date = "[ ](text)"
ahead = "[ ](sapphire)"
behind = "[ ](lavender)"
diverged = "[󰃻 ](maroon)"
conflicted = "[ ](red)"
staged = "[ ](green)"
deleted = "[ ](yellow)"
renamed = "[ ](yellow)"
modified = "[≡ ](yellow)"
typechanged = "[ ](yellow)"
untracked = "[ ](yellow)"
stashed = "[󰜦 ](rosewater)"

[docker_context]
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile', 'compose.yml', 'compose.yaml']

[character]
success_symbol = '[_](bold green)'
error_symbol = '[_](bold red)'

[time]
format = '[$time]($style) '
disabled = false

[fill]
symbol = ''

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
